// Angular/src/app/components/todo/todo.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

import { Todo } from '../../models/todo.model';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent {
  @Input() todo: Todo;
  @Input() index: number;
  @Output() deletedTodo = new EventEmitter();

  constructor(private todoService: TodoService) { }

  async handleIsDone(id: string) {
    try {
      await this.todoService.updateTodoStatus(id);
      this.todo.isDone = !this.todo.isDone;
    } catch (e) {
      console.error(e);
    }
  }

  async handleTodoDelete(theListWrapper: HTMLInputElement) {
    theListWrapper.style.animation = 'slideOut 1s forwards';
    theListWrapper.addEventListener('animationend', emitDeletedEvent.bind(this));
    async function emitDeletedEvent() {
      theListWrapper.removeEventListener('animationend', emitDeletedEvent);
      try {
        await this.todoService.deleteTodo(this.todo.id);
        this.deletedTodo.emit(this.index);
      } catch (e) {
        theListWrapper.style.animation = 'slideIn 500ms ease-out forwards 1';
      }
    }
  }
}

<div class="listWrapper" #theListWrapper>
  <div
    class="theList"
    [ngClass]="{ isDone: todo.isDone}"
    (click)="handleIsDone(todo.id, index)">

    <div>
      <label class="theList__label" for="status">{{ todo.content }}</label>
    </div>
    <input type="checkbox" class="status">

    <span class="check">
      <svg width="18px" height="18px" viewBox="0 0 18 18">
        <path
          d="M1,9 L1,3.5 C1,2 2,1 3.5,1 L14.5,1 C16,1 17,2 17,3.5 L17,14.5 C17,16 16,17 14.5,17 L3.5,17 C2,17 1,16 1,14.5 L1,9 Z"
        ></path>
        <polyline points="1 9 7 14 15 4"></polyline>
      </svg>
    </span>
  </div>

  <app-todo-delete
    [id]="todo.id"
    (deletedTodo)="handleTodoDelete(theListWrapper)"
  ></app-todo-delete>
</div>

// src/components/todo.vue
<template>
  <div class="listWrapper">
    <div class="theList" v-bind:class="{ isDone: isDone }" @click="handleIsDone(index)">
      <div>
        <label class="theList__label" for="status">{{ content }}</label>
      </div>
      <input type="checkbox" class="status">
      <span class="check">
        <svg width="18px" height="18px" viewBox="0 0 18 18">
          <path
            d="M1,9 L1,3.5 C1,2 2,1 3.5,1 L14.5,1 C16,1 17,2 17,3.5 L17,14.5 C17,16 16,17 14.5,17 L3.5,17 C2,17 1,16 1,14.5 L1,9 Z"
          ></path>
          <polyline points="1 9 7 14 15 4"></polyline>
        </svg>
      </span>
    </div>
    <delete-todo v-bind="{removeTodo, index}"></delete-todo>
  </div>
</template>

<script>
import DeleteTodo from "./DeleteTodo.vue";

export default {
  name: "TodoList",
  props: ["content", "isDone", "handleIsDone", "removeTodo", "index"],
  components: {
    DeleteTodo
  }
};
</script>
